import os
import requests

import os
import requests

def generate_ai_explanation(change_type, table, column, operation, downstream_tables, downstream_dashboards, suggested_fix):
    """
    Generate a natural language explanation of the breaking change.
    Falls back to template if AI API is unavailable.
    """
    prompt = f"""
You are a data engineer assistant. A Pull Request is trying to {operation} {column} from table {table}.
Downstream impact:
- {len(downstream_tables)} tables will break: {', '.join(downstream_tables[:3])}
- {len(downstream_dashboards)} dashboards will break: {', '.join(downstream_dashboards[:3])}
Suggested fix: {suggested_fix}

Write a SHORT, CLEAR warning message for the PR comment. Use emojis. Be helpful, not scary.
"""
    # Try OpenAI
    api_key = os.getenv("OPENAI_API_KEY")
    if api_key:
        try:
            resp = requests.post(
                "https://api.openai.com/v1/chat/completions",
                headers={"Authorization": f"Bearer {api_key}"},
                json={
                    "model": "gpt-3.5-turbo",
                    "messages": [{"role": "user", "content": prompt}],
                    "temperature": 0.7,
                    "max_tokens": 200
                },
                timeout=5
            )
            if resp.status_code == 200:
                return resp.json()["choices"][0]["message"]["content"]
        except Exception as e:
            print(f"OpenAI failed: {e}")

    # Try Ollama (free local)
    ollama_host = os.getenv("OLLAMA_HOST")
    if ollama_host:
        try:
            resp = requests.post(
                f"{ollama_host}/api/generate",
                json={"model": "llama2", "prompt": prompt, "stream": False},
                timeout=10
            )
            if resp.status_code == 200:
                return resp.json().get("response", "")
        except Exception as e:
            print(f"Ollama failed: {e}")

    # Fallback: template
    return f"""⚠️ **Breaking Change Detected**

You are trying to **{operation}** `{column}` from table `{table}`.

**Impact:**
- 🔻 {len(downstream_tables)} downstream tables will break
- 📊 {len(downstream_dashboards)} dashboards will be affected

**Suggested Fix:** {suggested_fix}

Please review before merging."""


def generate_report(violations: list, warnings: list, impacts: list) -> str:
    lines = [
        "## 📋 OpenMetadata Governance Report",
        "",
        "### 🔍 Impact Analysis",
        "| Table | Downstream Count | Severity |",
        "|-------|------------------|----------|"
    ]
    for imp in impacts:
        lines.append(f"| `{imp['table']}` | {imp['count']} | {imp['severity']} |")

    if violations:
        lines.extend(["", "### ❌ Breaking Changes", ""])
        for v in violations:
            # If this violation has AI explanation data, use it
            if v.get("ai_explanation"):
                lines.append(v["ai_explanation"])   # already formatted
            else:
                lines.append(f"- **{v['table']}**: {v['message']}")
            lines.append("")   # blank line between issues

    if warnings:
        lines.extend(["", "### ⚠️ Quality Warnings", ""])
        for w in warnings:
            lines.append(f"- **{w['table']}**: {w['message']}")

    lines.append("\n---\n*Report generated by OpenMetadata Data Contract Validator*")
    return "\n".join(lines)